workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "TKMServicekz.xcworkspace"
        XCODE_SCHEME: "MedianIcons"
    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
          pod install

      - name: Build unsigned IPA
        script: |
          xcode-project use-workspace
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa
